### ISSUE TITLE
CLI Error

### ISSUE THREAD

**Issue by ericdmoore** [federalies/CharlieHatfield#1]
Config file is:

```javascript
#! .squals.config.ts

export default {
  configList: [
    {
      typesPrefix: [
        'AWS::AppSync::',
        'AWS::Amplify::',
        'AWS::ApiGateway::',
        'AWS::ApiGatewayV2',
        'AWS::Athena::',
        'AWS::Budgets::Budget',
        'AWS::CertificateManager::',
        'AWS::CloudFormation::',
        'AWS::CloudFront::',
        'AWS::CodeBuild::',
        'AWS::Cognito::',
        'AWS::CodeCommit::',
        'AWS::CodeDeploy::',
        'AWS::CodePipeline::',
        'AWS::DynamoDB::',
        'AWS::Lambda::',
        'AWS::KinesisFirehose::',
        'AWS::Route53::',
        'AWS::S3::',
        'AWS::SES::',
        'AWS::SNS::',
        'AWS::SQS::'
      ]
    }
  ]
}
```

gives a `Properties` is undefined uncaught exception error

```bash
printer:: src/.squals.config.ts
{ configFileStrings: [ 'src/.squals.config.ts' ] }
(node:85961) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Properties' of undefined
    at SqualsFile.__methods (/projects/CharlieHatfield/src/sourceFile.ts:402:31)
    at SqualsFile.<anonymous> (/projects/CharlieHatfield/src/sourceFile.ts:305:18)
    at Generator.next (<anonymous>)
    at /projects/CharlieHatfield/src/sourceFile.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/projects/CharlieHatfield/src/sourceFile.ts:3:12)
    at SqualsFile.genMethods (projects/CharlieHatfield/src/sourceFile.ts:222:16)
    at SqualsFile.<anonymous> (/projects/CharlieHatfield/src/sourceFile.ts:251:25)
    at Generator.next (<anonymous>)
    at fulfilled (/projects/CharlieHatfield/src/sourceFile.ts:4:58)
(node:85961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:85961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
- - - - I then manually exited ^C
```

**Comment by ericdmoore** [comment]
SES was not available in the spec.
CLI choked - see data folder for more detail on dirty data and how we will handle it

**Comment by ericdmoore** [comment]
commit: ff0bb7c805102de07ca1fd3e3681e9325018113d fixed this.
